### ISSUE TITLE
Sources should return a non-null VoxelDimensions

### ISSUE THREAD

**Issue by bogovicj** [bigdataviewer/bigdataviewer-vistools#42]
`AbstractSource`s, and therefore `RandomAccessibleIntervalSource` [return a null `VoxelDimensions`](https://github.com/bigdataviewer/bigdataviewer-vistools/blob/1322f4c6c9ba6f35353c90ea1954cd43b156854b/src/main/java/bdv/util/AbstractSource.java#L87).

I think I'd prefer returning a "default" with spacings of "1" with units of "pixels" or "voxels".  Without this, anything depending on a `Source` that uses `VoxelDimensions` have to check whether it's `null` or not (e.g. bigwarp [- see this gitter conversation](https://gitter.im/bigdataviewer/bigdataviewer-core?at=5e0fa5a63062aa3e8dee9c9b))

Any objections?

@hanslovsky 
@kephale
@tpietzsch 
@axtimwalde

**Comment by axtimwalde** [comment]
Agree.

**Comment by hanslovsky** [comment]
I am OK with a returning a reasonable non-`null` default `VoxelDimension`. It does not affect me either way because I ignore the `VoxelDimensions` in all my projects, for two reasons:
 1. In Paintera, "global" space is in nano meters (implicit). 
 2. The meaning of `VoxelDimensions` is not entirely clear to me. Is it the size of a voxel of the transformed source in global space? Or is it the size of the transformed source before the transformation is applied? Does the source transform encode the `VoxelDimensions` anyway?

**Comment by bogovicj** [comment]
Well, the above has the easiest reasonable, non-breaking fix.

With the complication that, to prevent this from changing the constructor of `AbstractSource`, 
the default voxeldimensions itself can't know how many dimensions it has, so [this looks ugly](https://github.com/bogovicj/bigdataviewer-vistools/blob/ac5843a7853abfdae50d6eceda1ed3ca778ca675/src/main/java/bdv/util/AbstractSource.java#L62). 

Should have written in the comment that the number of dimensions there does not matter, since 
[`DefaultVoxelDimensions` will always return `1` as its spacing.](https://github.com/bogovicj/bigdataviewer-vistools/blob/ac5843a7853abfdae50d6eceda1ed3ca778ca675/src/main/java/mpicbg/spim/data/sequence/DefaultVoxelDimensions.java#L24-L35).

If we're okay with this, I can PR (after giving a documenting the new [`DefaultVoxelDimensions` class](https://github.com/bogovicj/bigdataviewer-vistools/blob/ac5843a7853abfdae50d6eceda1ed3ca778ca675/src/main/java/mpicbg/spim/data/sequence/DefaultVoxelDimensions.java).

**Comment by tpietzsch** [comment]
sounds good

**Comment by bogovicj** [comment]
PR #43 merged.  Thanks!
